config/routes.rb
Rails.application.routes.draw do

  get 'courses/index'
  # resources :meetings
  resources :reservations

  
  devise_for :admins, controllers: { registrations: 'registrations' }
  

  resources :shops, only: [:new, :edit]
  resources :admins, only: [:index, :update, :destroy, :new]
  resources :questions, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :admins, only: [] do
    collection do
      post :generate
    end
  end
  
  resources :menus, only: [] do
    resources :courses, only: :index
  end

  resources :menus, only: [:edit,:create, :update, :delete]
  root 'menus#top'
  get 'change/schedule' => "reservations#change_schedule", as: "change_schedule"
  get 'menus/top' => "menus#top", as: "top"
  get 'menus/course' => "menus#course", as: "course"
  post 'menus/course' => "menus#create", as: "course_new"
  get 'menus/access' => "menus#access", as: "access"
  get 'menus/note' => "menus#note", as: "note"
  get 'menus/add' => "menus#add", as: "add_menu"
  get '/menus/:id/edit_menu' => "menus#edit_menu", as: "renew_menu"
  patch '/menus/:id/edit_menu' => "menus#update_menu"
  delete '/menus/:id/edit_menu' => "menus#destroy"
  
  get 'all_reservations/index' => "reservations#all_index", as: "all_reservations_index"
  get 'all_reservations/:id/show' => "reservations#all_show", as: "all_reservations_show"


end

app/models/question.rb
class Question < ApplicationRecord
  validates :user_question, presence: true, length: { maximum: 100 }
  validates :answer, presence: true, length: { maximum: 200 }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def index
    @question = Question.new
    @questions = Question.all
  end
  
  def create
    question = Question.new(question_params)
    if question.save
      flash[:success] = "登録しました。"
      redirect_to questions_path
    else
      flash[:danger] = "登録に失敗しました。"
      redirect_to questions_path
    end
  end
  
  def edit
    @question = Question.find(params[:id])
  end
  
  def update
    @question = Question.find(params[:id])
    if  @question.update(question_params)
        flash[:success] = "更新しました。"
        redirect_to questions_path
    else
      flash[:danger] = "更新に失敗しました。"
        render :edit
    end
  end
  
  def destroy
    question = Question.find(params[:id])
    if question.destroy
      flash[:success] = "削除しました。"
    else
      flash[:danger] = "削除に失敗しました。"
    end
    redirect_to questions_path
  end
  
  private
  
  def question_params
    params.require(:question).permit(:user_question, :answer)
  end
  
end

app/views/questions/edit.html.erb
 <div class="main">
  <div class="block">
      <h2 class="bg_sunflower">Q&Aを編集する</h2>
    <div class="contents">
  <%= form_with(model: @question, url:question_path, local: true) do |f| %>
     <%= render "devise/shared/error_messages", resource: @question %>
      <div class="form">
			<dl>
				<dt class="form-title">質問</dt>
				<dd class="form-item"><%= f.text_field :user_question, required: "required", class: "col-10" %></dd>
			</dl>
		</div>
		<div class="form">
			<dl>
				<dt class="form-title">回答</dt>
				<dd class="form-item"><%= f.text_area :answer, required: "required", class: "col-10" %></dd>
			</dl>
		</div>
      </div>
        <%= f.submit "更新する", class: "btn btn-info btn-lg px-5" %>
    <% end %>
     </div> 
 </div>
</div>

app/views/questions/index.html.erb
<div class="main">
  <div class="block">
    <h2 class="bg_sunflower">よくあるご質問</h2>
      <div class="contents pb-3" id="faq_block">
        <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
          <% @questions.each_with_index do |question, i|%>
            <div class="card my-5">
              <div class="card-header bg-blue" role="tab" id="heading<%= i %>">
                <h5 class="mb-0">
                  <a class="text-body d-block p-3 m-n3" data-toggle="collapse" href="#collapse<%= i %>" role="button" aria-expanded="true" aria-controls="collapse<%= i %>">
                    Q.<%= question.user_question %>
                  </a>
                  <% if admin_signed_in? %>
                   <span class="float-right">
                    <%= link_to edit_question_path(question.id), class: "btn btn-lg btn-primary px-4" do %>
                      <i class="fas fa-pen"></i>　編集
                    <% end %>
                    <%= link_to question_path(question.id, permission: true), delete: "question", method: :delete,"data-confirm" => "本当に削除しますか？", class: "btn btn-lg px-4 btn-primary" do %>
                      <i class="fas fa-trash"></i>　削除
                    <% end %>
                    </span>
                  <% end %>
                </h5>
              </div><!-- /.card-header -->
              <div id="collapse<%= i %>" class="collapse" role="tabpanel" aria-labelledby="heading<%= i %>" data-parent="#accordion">
                <div class="card-body">
                  A.<%= question.answer %>
                </div><!-- /.card-body -->
              </div><!-- /.collapse -->
            </div><!-- /.card -->
          <% end %>
        </div><!-- /.accordion -->
      </div>
  </div>
  <% if current_admin %>
    <div class="hidden_box mb-4">
      <label for="label1" class="btn btn-primary btn-lg px-5 cursor-button mx-3">
        <i class="fas fa-plus-circle"></i>　Q&Aを追加
      </label>
      <input type="checkbox" id="label1" style="display: none;"/>
        <div class="hidden_show">
          <!--非表示ここから-->
          <div class="contents">
            <div class="form">
              <dl>
                <%= form_with(model: @question, url: questions_path ,local: true) do |f| %>
                  <dt class="form-title">質問文</dt>
                  <dd class="form-item"><%= f.text_field :user_question, required: "required", maxlength: 100, class: "col-10" %></dd>
                  <dt class="form-title">答え</dt>
                  <dd class="form-item"><%= f.text_area :answer, required: "required", maxlength: 200 %></dd>
                  <%= f.submit "追加する", class: "btn btn-info btn-lg offset-5 px-5" %>
                <% end %>
              </dl>
            </div>
            <!--ここまで-->
          </div>
        </div>
    </div>
  <% end %>
</div>