config/routes.rb
Rails.application.routes.draw do

  get 'courses/index'
  # resources :meetings
  resources :reservations

  
  devise_for :admins, controllers: { registrations: 'registrations' }
  

  resources :shops, only: [:new, :edit]
  resources :admins, only: [:index, :update, :destroy, :new]
  resources :questions, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :admins, only: [] do
    collection do
      post :generate
    end
  end
  
  resources :menus, only: [] do
    resources :courses, only: :index
  end

  resources :menus, only: [:edit,:create, :update, :delete]
  root 'menus#top'
  get 'change/schedule' => "reservations#change_schedule", as: "change_schedule"
  get 'menus/top' => "menus#top", as: "top"
  get 'menus/course' => "menus#course", as: "course"
  post 'menus/course' => "menus#create", as: "course_new"
  get 'menus/access' => "menus#access", as: "access"
  get 'menus/note' => "menus#note", as: "note"
  get 'menus/add' => "menus#add", as: "add_menu"
  get '/menus/:id/edit_menu' => "menus#edit_menu", as: "renew_menu"
  patch '/menus/:id/edit_menu' => "menus#update_menu"
  delete '/menus/:id/edit_menu' => "menus#destroy"
  
  get 'all_reservations/index' => "reservations#all_index", as: "all_reservations_index"
  get 'all_reservations/:id/show' => "reservations#all_show", as: "all_reservations_show"


end

app/models/menu.rb
class Menu < ApplicationRecord
	has_many :courses
	has_many :reservations
	accepts_nested_attributes_for :courses
	mount_uploader :image, ImageUploader
	
	validates :menu_title, presence: true, length: { maximum: 50 }, uniqueness: true
	validates :introduce, presence: true, length: { maximum: 200 }
	# validates :image, file_size: { less_than_or_equal_to: 1000.kilobytes }
	validate  :image_size
                     
    # アップロードされた画像のサイズをバリデーションする
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "容量は5MB以下にしてください。")
      end
    end

	
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def top
  end

  def course
    @menus = Menu.all.order(:created_at)
    @menu = Menu.new
    @menu.courses.build
  end

  def access
  end

  def note
  end


  def add
    @menu = Menu.new
  end

  def edit_menu
    @menu = Menu.find(params[:id])
  end


  def update_menu
    menu = Menu.find(params[:id])
    if  menu.update(menu_params)
        flash[:success] = "更新しました。"
    else
      flash[:danger] = "更新に失敗しました。"
        render :edit
    end
    redirect_to course_path
  end

  def destroy_menu
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
      if params[:permission] == "true"
        @menu = Menu.new(menu_params)
        # byebug
        if @menu.save
          flash[:success] = "登録しました。"
          redirect_to course_path
        else
          flash[:danger] = "登録に失敗しました。"
          render :add
        end
      elsif params[:permission] == "false"
        @course = Course.new(menu_course_params)
        if @course.save
          flash[:success] = "登録しました。"
          redirect_to course_path
        else
          flash[:danger] = "同じメニュー内にコース名が重複しているため、登録に失敗しました。"
          redirect_to course_path
        end
      end
  end

  def update
    if params[:permission] == "true"
      @menu = Menu.find(params[:id])
      if @menu.update(menu_params)
          flash[:success] = "更新しました。"
          redirect_to course_path
      else
        flash[:danger] = "更新に失敗しました。"
        render :edit_menu
      end
    elsif params[:permission] == "false"
      @course = Course.find(params[:id])
      if @course.update(course_params)
          flash[:success] = "更新しました。"
          redirect_to course_path
      else
        flash[:danger] = "更新に失敗しました。"
          render :edit
      end
    end
  end

  def destroy
    if params[:permission]
      if params[:permission] == "true"
        menu = Menu.find(params[:id])
        menu.destroy
        flash[:sccess] = "削除しました。"
      elsif params[:permission] == "false"
        course = Course.find(params[:id])
        course.destroy
        flash[:danger] = "削除しました。"
      end
    end
    redirect_to course_path
  end

  private
  def menu_params
    params.require(:menu).permit(:menu_title, :introduce, :image)
  end

  def menu_course_params
    params.require(:menu).permit(:menu_id, [:course_name, :course_time, :price])
  end

  def course_params
    params.require(:course).permit(:course_name, :course_time, :price)
  end


end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/access.html.erb
<% set_meta_tags title: "アクセスページ" %>
<% set_meta_tags description: "ichiのアクセスページです" %>
<div class="main">
  <div class="block">
    <h2 class="bg_sunflower">アクセス</h2>
    <div class="contents">
      <p>
        <i class="fas fa-map-marker-alt my-blue"></i>
          東京都板橋区成増<br>(※プライベートサロンのため、住所の詳細は、ご予約いただいたお客様にのみにお電話にてお伝えいたします。)<br>
          東武東上線 成増駅から徒歩2分<br>
          東京メトロ副都心線 地下鉄成増駅から徒歩1分
      </p>
      <br>
      <p><i class="fas fa-phone fa-flip-horizontal my-blue"></i> 03-6904-1073</p>
      <p>トリートメント中は電話に出る事ができませんので、メッセージ(お名前、ご連絡先)を残して頂ければ折り返しご連絡いたします。</p>
      <br>
      <p><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3236.9171812923323!2d139.63096071526144!3d35.77741068017201!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6018ec75b1cc3f83%3A0x7701f73700145a5f!2z5oiQ5aKX6aeF!5e0!3m2!1sja!2sjp!4v1562093639562!5m2!1sja!2sjp" width="100%" height="500px;" frameborder="0" style="border:0" allowfullscreen></iframe></p>
     </div>
  </div>
</div>

app/views/menus/add.html.erb
<div class="main">
  <div class="block">
      <h2 class="bg_sunflower">メニューの追加</h2>
    <div class="contents">
  <%= form_with(model: @menu,local: true) do |f| %>
   <%= render "devise/shared/error_messages", resource: @menu %>
      <div class="form">
			<dl>
				<dt class="form-title">メニュー名</dt>
				<dd class="form-item"><%= f.text_field :menu_title, required: true %></dd>
			</dl>
		</div>
		<div class="form">
			<dl>
				<dt class="form-title">画像1</dt>
				<dd class="form-item"><%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %></dd>
				<p>画像サイズは640×480が最適なサイズです。</p>
			</dl>
		</div>
		<div class="form">
			<dl>
				<dt class="form-title">紹介文</dt>
				<dd class="form-item"><%= f.text_area :introduce, required: true  %></dd>

				<%= hidden_field_tag :permission, true %>
			</dl>
      </div>
        <%#= f.hidden_field :menu_id, value: false%>
        <%= f.submit "追加する", class: "btn btn-info btn-lg px-5 offset-5" %>
    <% end %>
     </div> 
 </div>
</div>

app/views/menus/course.html.erb
<div class="main">
	<div class="block　course_block">
		<h2 class="bg_sunflower">メニュー・コース一覧</h2>
		<% if current_admin %>
		<div class="">
			<%= link_to add_menu_path, class: "btn btn-info btn-lg mt-3 px-5 offset-md-5 offset-lg-0 offset-3" do %>
			 <i class="fas fa-plus-circle"></i>　メニュー追加
			<% end %>
			</div>
		<% end %>
		<div class="contents">
		  <% @menus.each.with_index do |menu, i| %>
		    <div class="my-5">
					<h3 class="menu_title">
						<%= menu.menu_title %>
					</h3>
						<% if admin_signed_in? %>
							<span class="">
	  		   		<%= link_to renew_menu_path(menu.id), class: "btn btn-info btn-lg px-5 no-text-indent mx-3" do %>
	  		   			<i class="fas fa-pen"></i>　編集
	  		   		<% end %>
	  		    	<%= link_to renew_menu_path(menu.id, permission: true), delete: "menu", method: :delete,"data-confirm" => "本当に削除しますか？", class: "btn btn-info no-text-indent btn-lg px-5" do %>
	  		    		<i class="fas fa-trash"></i>　削除
	  		    	<% end %>
	  		    	<span class="hidden_box contents p-0 d-inline">
      					<label for="label<%= i %>" class="btn btn-info btn-lg px-5 cursor-button mx-3">
      						<i class="fas fa-plus-circle"></i>　コース追加
      					</label>
      					<input type="checkbox" id="label<%= i %>" style="display: none;"/>
      					<div class="hidden_show" style="clear: both;">
  								<dt class="form-title">【コースの追加】</dt>
  								<%= form_with(model: @menu, url: menus_path, method: :post ,local: true) do |f| %>
  	    						<div class="form-group row mt-3">
            					<%= f.label "コース名", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            					<%= f.text_field :course_name, id: "course_name#{i}", required: true, maxlength:50 %>
        						</div>
        						<div class="form-group row">
            					<%= f.label "コース時間", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            					<%= f.select :course_time, [["30", 30], ["60", 60], ["90", 90], ["120", 120], ["150", 150], ["180", 180]], id: "menu_course_time#{i}" %>　分
        						</div>
        						<div class="form-group row">
           						<%= f.label "価格", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
           						<%= f.number_field :price, id: "menu_price#{i}", required: true, min:0 %>　円
       							</div>
  	   							<%= f.hidden_field :menu_id, value: menu.id, id: "menu_id{i}" %>
        						<%= hidden_field_tag :permission, false, id: "permission#{i}" %>
  	      					<%= f.submit "追加する", class: "btn btn-primary btn-lg px-5 offset-5" %>
  	    					<% end %>
								</div>
							</span>
	  		   		</span>
	  		   	<% end %>
	  			<div class="course_description">
	  		  	<p class="course_photo">
	  		  		<!--<%# if i == 0 %>-->
	  		  			<%#= image_tag 'massage2.jpg' %>
	  		  		<!--<%# elsif i == 1 %>-->
	  		  		<!--	<%#= image_tag 'foot.jpg' %>-->
	  		  		<!--<%# elsif i == 2 %>-->
	  		  		<!--	<%#= image_tag 'tyou.jpg' %>-->
	  		  		<!--<%# elsif i == 3 %>-->
	  		  		<!--	<%#= image_tag 'HyperKnife.jpg' %>-->
	  		  		<% if menu.image.present? %>
	  		  			<%#= image_tag(menu.image_url, :alt => menu.menu_title) %>
	  		  			<%= cl_image_tag(menu.image_url(:standard), width: 100, height: 100) %>
								<%# <%= image_tag("/images/no_image.jpg", :alt => menu.menu_title) %>
	  		  		<% else %>
	  		  			<%= image_tag("/images/no_image.jpg", :alt => menu.menu_title) %>
	  		  		<% end %>

	  		   	</p>
	  		   	<p class="course_text pl-md-5"><%= menu.introduce %></p>
	  			</div>
        	<div class="course_box my-5" style="clear: both;">
	        	<% menu.courses.order(:course_time).each do |course| %>
	        	<% if admin_signed_in? %>

	        			<span class="float-right">
	      				<%= link_to edit_menu_path(course.id), class: "btn btn-primary btn-lg" do %>
	      					<i class="fas fa-pen"></i>　編集
	      				<% end %>
	      		  	<%= link_to renew_menu_path(course.id, permission: false), delete: "course", method: :delete,"data-confirm" => "本当に削除しますか？", class: "btn btn-lg btn-info" do %>
	      		  		<i class="fas fa-trash"></i>　削除
	      		  	<% end %>
	      		  	</span>

	      			<% end %>
	      			<dl class="mx-auto">
	      				<dt><%= course.course_name %></dt>
	      				<dd><%= course.course_time %>分</dd>
	      				<dd><%= course.price %>円</dd>
	      			</dl>
	    			<% end %>
	    		</div>
				</div>
				<br>
			<% end %>
		</div>
	</div>
</div>


app/views/menus/edit.html.erb
<div class="main">
  <div class="block">
      <h2 class="bg_sunflower">コースを編集する</h2>
    <div class="contents">
  <%= form_with(model: @course, url: menu_path,local: true) do |f| %>
      <div class="form">
			<dl>
				<dt class="form-title">コース名</dt>
				<dd class="form-item"><%= f.text_field :course_name, required: true, maxlength: 50, class: "" %></dd>
			</dl>
		</div>
		<div class="form">
			<dl>
				<dt class="form-title">コース時間</dt>
				<dd class="form-item"><%= f.select :course_time, [["30", 30], ["60", 60], ["90", 90], ["120", 120], ["150", 150], ["180", 180]], class: "" %>分</dd>
			</dl>
		</div>
		<div class="form">
			<dl>
				<dt class="form-title">価格</dt>
				<dd class="form-item"><%= f.number_field :price, required: true, min: 0, class: "" %>円</dd>

				<%= hidden_field_tag :permission, false %>
			</dl>
      </div>
        <%#= f.hidden_field :menu_id, value: false%>
        <%= f.submit "更新する", class: "btn btn-info btn-lg px-5 offset-5" %>
    <% end %>
     </div> 
 </div>
</div>

app/views/menus/edit_menu.html.erb
<div class="main">
  <div class="block">
      <h2 class="bg_sunflower">メニューを編集する</h2>
    <div class="contents">
  <%= form_with(model: @menu,local: true) do |f| %>
   <%= render "devise/shared/error_messages", resource: @menu %>
      <div class="form">
			<dl>
				<dt class="form-title">メニュー名</dt>
				<dd class="form-item"><%= f.text_field :menu_title, required: true, class: "col-10" %></dd>
			</dl>
		</div>
		<div class="form">
			<dl>
				<dt class="form-title">画像1</dt>
				<dd class="form-item"><%#= image_tag(@menu.menu_image_url(:thumbnail), :width => 80, :height => 80) %></dd>
				<dd class="form-item">
					<%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
					<p>画像サイズは640×480が最適なサイズです。</p>
				</dd>
			</dl>
		</div>
		<div class="form">
			<dl>
				<dt class="form-title">紹介文</dt>
				<dd class="form-item"><%= f.text_area :introduce, required: true, class: "col-10" %></dd>

				<%= hidden_field_tag :permission, true %>
			</dl>
      </div>
        <%#= f.hidden_field :menu_id, value: false%>
        <%= f.submit "更新する", class: "btn btn-info btn-lg px-5 offset-5" %>
    <% end %>
     </div> 
 </div>
</div>

app/views/menus/edit_note.html.erb
 <div class="main">
  <div class="block">
      <h2 class="bg_sunflower">Q&Aを編集する</h2>
    <div class="contents">
  <%= form_with(model: @question, url:edit_note_path, local: true) do |f| %>
     <%= render "devise/shared/error_messages", resource: @question %>
      <div class="form">
			<dl>
				<dt class="form-title">質問</dt>
				<dd class="form-item"><%= f.text_field :user_question, required: "required", class: "col-10" %></dd>
			</dl>
		</div>
		<div class="form">
			<dl>
				<dt class="form-title">回答</dt>
				<dd class="form-item"><%= f.text_area :answer, required: "required", class: "col-10" %></dd>
			</dl>
		</div>
      </div>
        <%= f.submit "更新する", class: "btn btn-info btn-lg px-5" %>
    <% end %>
     </div> 
 </div>
</div>

app/views/menus/menus.html.erb
<div class="contents">
<h2>コースの追加</h2>
	<%= form_with(model: @menu,local: true) do |f| %>
      <div class="form">
        <h4>メニュー名</h4>
        <%= f.text_field :menu_title %>
        <h4>画像</h4>
        <%= f.attachment_field :menu_image %>
      </div>
      <div class="form">
        <h4>紹介文</h4>
        <%= f.text_area :introduce %>
        <%= f.hidden_field :permission, value: true %>
      </div>
        <%#= f.hidden_field :menu_id, value: false%>
        <%= f.submit "追加する" %>
    <% end %>

    </div>

app/views/menus/note.html.erb
<div class="main">
  <div class="block">
    <h2 class="bg_sunflower">注意事項</h2>
    <div class="contents">
      <p style="color: red; font-size: 14px; font-weight: bold;">
        ※以下の注意事項はご予約前に必ずお読みください。
      </p>
      当サロンの施術は、リラクゼーションやリフレッシュ、美と健康の維持増進を目的としております。<br>
      治療を目的としたものではありません。
      <br>
      <br>
      <p>次の項目のいずれかに当てはまる場合は、お受けいたしかねますのでご了承下さい。</p>

      <ul>
        <li>医師による治療を受けている方、又は医師の許可を得ていない方</li>
        <li>妊娠している可能性のある方</li>
        <li>発熱している、極度に体力を消耗している方</li>
        <li>飲酒をした状態の方</li>
        <li>手術後間もない方</li>
        <li>皮膚疾患、水虫の方</li>
        <li>ガン、心臓病、高血圧、腎臓疾患、糖尿病、リウマチ、 骨粗しょう症の方、てんかんをお持ちの方</li>
        <li>けが、やけど、打撲、捻挫などの急性の炎症がある方</li>
        <li>椎間板ヘルニア、ムチウチ、すべり症、分離症の方</li>
      </ul>
    </div>
  </div>
  
  <div class="block">
    <h2 class="bg_pinkflower">ご予約変更・キャンセルについて</h2>
    <div class="contents">
      <ul>
        <li>日時変更は、ご予約日の「前日」までにご連絡をお願い致します</li>
        <li>当日キャンセルされた場合、キャンセル料としてトリートメント代金の全額を頂戴いたします</li>
        <li>ご予約時間開始から15分以上過ぎた場合は、セラピーの時間を短縮、または当日セラピーが出来ない場合がございます (次の時間にご予約を頂いているお客様に影響が出てしまう為です)</li>
        <li>当日セラピーが出来なかった場合、当日キャンセルと同じ扱いとなります</li>
      </ul>
      <br>
      <p>ichiに来てくださるお客様に快適なお時間を過ごして頂けるよう、メニューや状況に合わせてご予約時間の設定をしております。</p>
      <p>当日の遅刻、当日キャンセル、無断キャンセルは、予約を取りたい他のお客様に大変ご迷惑となります。</p>
      <p>お客様に気持ち良く通って頂けるよう、大変恐縮ではございますが、ご理解ご協力のほど、よろしくお願い申し上げます。</p>
    </div>
  </div>
</div>