config/routes.rb
Rails.application.routes.draw do

  get 'courses/index'
  # resources :meetings
  resources :reservations

  
  devise_for :admins, controllers: { registrations: 'registrations' }
  

  resources :shops, only: [:new, :edit]
  resources :admins, only: [:index, :update, :destroy, :new]
  resources :questions, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :admins, only: [] do
    collection do
      post :generate
    end
  end
  
  resources :menus, only: [] do
    resources :courses, only: :index
  end

  resources :menus, only: [:edit,:create, :update, :delete]
  root 'menus#top'
  get 'change/schedule' => "reservations#change_schedule", as: "change_schedule"
  get 'menus/top' => "menus#top", as: "top"
  get 'menus/course' => "menus#course", as: "course"
  post 'menus/course' => "menus#create", as: "course_new"
  get 'menus/access' => "menus#access", as: "access"
  get 'menus/note' => "menus#note", as: "note"
  get 'menus/add' => "menus#add", as: "add_menu"
  get '/menus/:id/edit_menu' => "menus#edit_menu", as: "renew_menu"
  patch '/menus/:id/edit_menu' => "menus#update_menu"
  delete '/menus/:id/edit_menu' => "menus#destroy"
  
  get 'all_reservations/index' => "reservations#all_index", as: "all_reservations_index"
  get 'all_reservations/:id/show' => "reservations#all_show", as: "all_reservations_show"


end

app/models/reservation.rb
class Reservation < ApplicationRecord

  belongs_to :course
  belongs_to :menu

  require "time"

  # 過去の予約は無効
  validate :past_time_is_not_able_to_reservation, on: :create
  validate :not_sales_time_is_not_able_to_reservation

  validate :make_a_reservation_is_valid_on_reserved_time

	 def make_a_reservation_is_valid_on_reserved_time
    if (start_time.present? && finish_time.present?) && Reservation.where("start_time < ? and finish_time > ?",finish_time + (30 * 60), start_time - (30 * 60)).where.not(id: self.id).present?
      errors.add(:started_at, "入力された時間はすでに予約が入っています。")
    end
  end


  def past_time_is_not_able_to_reservation
    if start_time.present?
      errors.add(:started_at, "過去の時間は予約できません。") if start_time < Time.zone.now
    end
  end

  # 営業時間（10時〜21時）以外の予約は弾く
  def not_sales_time_is_not_able_to_reservation
    if start_time.present?
      date = start_time.strftime("%Y-%m-%d")
      if start_time < Time.parse("#{date} 1:00:00") || finish_time > Time.parse("#{date} 12:00:00")
        errors.add(:started_at, "営業時間外です。")
      end
    end
  end

  # 予約を絞り込み検索します。
  def self.search(search, search_date, search_history)


    if search.present? && search_date.present?
      where(['user_name LIKE ? OR user_phone_number LIKE ? OR user_kana_name LIKE ? OR demand LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
      .where(start_time: Time.parse("#{search_date}").all_day)
    elsif search_date.present?
      where(start_time: Time.parse("#{search_date}").all_day)
    elsif search.present?
      if search_history.present?
      where(['user_name LIKE ? OR user_phone_number LIKE ? OR user_kana_name LIKE ? OR demand LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
      .where('start_time <= ?', Time.current)
      else
        where(['user_name LIKE ? OR user_phone_number LIKE ? OR user_kana_name LIKE ? OR demand LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
        .where('start_time > ?', Time.current)
      end
    else
      if search_history.present?
        where('start_time <= ?', Time.current)
      else
        where('start_time > ?', Time.current)
      end
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @first_day = Date.current
    set_reservation_schedule
    # @reservations = Reservation.where(start_time: Time.zone.now..Float::INFINITY).order(start_time: :asc)
    @reservations = Reservation.all.order(start_time: :asc)
    @reservations_today = Reservation.where(start_time: Time.zone.now.all_day).order(start_time: :asc)
  end

  def new
    @reservation = Reservation.new
    gon.course_array = Course.all.order(:menu_id).pluck(:menu_id, :course_name)
    gon.course_time_array = Course.all.order(:menu_id).pluck(:menu_id, :course_name, :course_time)
    @today = Date.today
    @times24 = []
    minutes = ["00","30"]
    i = 0
    while(i <= 23) do
      minutes.each { |minute|
      @times24.push(i.to_s + ":" + minute)
      }
      i += 1
    end
    @selected_start_time = params[:start_time]
    @week_day = params[:week_day]

  end

  def destroy
    @reservation = Reservation.find(params[:id])
    Reservation.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to action: 'index'
  end


  def change_schedule
    if params[:prev]
      day = params[:prev]
    elsif params[:next]
      day = params[:next]
    end
    if day
      @first_day = day.to_date
      set_reservation_schedule
    end
  end

  def show
    @reservation = Reservation.all
    #既に予約されている日時を取得する
    @reservation.each do |res|
    day = res.start_time.year.to_s + "-" + res.start_time.month.to_s+ "-" + res.start_time.day.to_s
    puts day
    @reservation_time = []
    if res.start_time.min == 0
      start_min = res.start_time.min.to_s + "0"
      @reservation_time.push(res.start_time.hour.to_s + ":" + start_min)
    end
    @reservation_time.push(res.start_time.hour.to_s + ":" + res.start_time.min.to_s)
    puts @reservation_time
  end

    @times24 = []
    i = 0
    minutes = ["00","30"]
    while(i <= 23) do
      minutes.each { |minute|
      @times24.push(i.to_s + ":" + minute)
      }
      i += 1
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    gon.course_name = Course.find(@reservation.course_id).course_name
    gon.course_array = Course.all.order(:menu_id).pluck(:menu_id, :course_name)
    gon.course_time_array = Course.all.order(:menu_id).pluck(:menu_id, :course_name, :course_time)
  end


  def create
    @reservation = Reservation.new(reservation_params)
    course = Course.where(menu_id: params[:reservation][:menu_id]).find_by(course_name: params[:reservation][:course_name])
    if params[:is_holiday].present?
      @course_time = 630
      temp_start_time = @reservation.start_time.strftime("%Y-%m-%d")
      @reservation.start_time = Time.parse(temp_start_time + '-01:00')
    else
      @course_time = course.course_time.to_i
    end
    @reservation.finish_time = @reservation.start_time + @course_time.minutes
    @reservation.course_id = course.id
    if @reservation.save
      AddReservationMailer.add_reservation_mail(params[:reservation][:course_name], @reservation, @course_time).deliver_later
      AddReservationMailer.to_user_mail(params[:reservation][:course_name], @reservation, @course_time).deliver_later
      flash[:success] = "予約が完了しました。"
    else
      flash[:danger] = "予約日時を見直して再度ご予約ください。"
    end
    redirect_to action: 'index'
    logger.debug @reservation.errors.inspect
  end

  def update
    @reservation = Reservation.find(params[:id])
    course = Course.where(menu_id: params[:reservation][:menu_id]).find_by(course_name: params[:reservation][:course_name])
    @course_time = course.course_time.to_i
    @update_reservation = Reservation.new(reservation_params)
    @reservation.finish_time = @update_reservation.start_time + @course_time.minutes
    @reservation.course_id = course.id
    if @reservation.update_attributes(reservation_params)
      flash[:success] = "#{@reservation.user_name}様の基本情報を更新しました。"
    else
      flash[:danger] = "予約の更新は失敗しました。" + @reservation.errors.full_messages.join("/")
    end
    redirect_to action: 'index'
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    Reservation.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to action: 'index'
  end

  def all_index
    @reservations = Reservation.search(params[:search], params[:search_date], params[:search_history]).order(start_time: :asc).page(params[:page]).per(10)
  end

  def all_show
    @reservation = Reservation.find(params[:id])
  end


  private

  # def kari_params
  #   params.require(:reservation).permit(:user_name, :user_kana_name, :gender, :user_email, :user_phone_number, :start_time, :demand, :sales, :course_name, :request_course)
  # end


  private

  def set_reservation_schedule
      @week_day = (@first_day..@first_day.since(7.days))
      # @reservations = Reservation.where("finish_time > ?",Time.zone.now)
      @reservations = Reservation.all
      @times = 22.times.map.each_with_index {|i| Time.parse("10:00")+30.minutes*i}
      @time_number = 10.times.map.each_with_index {|i| l(Time.parse("11:00")+1.hours*i,format: :shorttime)}
  end

  def reservation_params
      params.require(:reservation).permit(:user_name, :user_kana_name, :user_email, :user_phone_number, :start_time, :demand, :menu_id, :birthday, :request_course_time)
    end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
  
  require 'holiday_jp'
  
  def get_color(week_day)
    if week_day == Date.current
      "week_today_color"
    elsif week_day.saturday? 
      "text-primary"
    elsif week_day.sunday? || HolidayJp.holiday?(week_day)
      "text-danger"
    end
  end 
  
  def get_height(start_time,finish_time,week_day)
    if Date.parse(start_time.to_s) == Date.parse(finish_time.to_s)
      time = ((finish_time - start_time + 1800)/60/60)
      (time/24.to_f*1776)
    elsif Date.parse(start_time.to_s) == week_day
      time = ((week_day.end_of_day - start_time)/60/60)
      (time/24.to_f*1776)
    elsif Date.parse(finish_time.to_s) == week_day
      time = ((finish_time - week_day.midnight)/60/60)
      (time/24.to_f*1776)
    elsif Date.parse(finish_time.to_s) > week_day && Date.parse(start_time.to_s) < week_day
      1776
    end
  end
  
  def get_position(start_time,finish_time,week_day)
    if Date.parse(start_time.to_s) == Date.parse(finish_time.to_s) || Date.parse(start_time.to_s) == week_day
       time = ((start_time - week_day.midnight)/60/60 - 10)
       (time/11.to_f*814)
    elsif Date.parse(finish_time.to_s) == week_day || (Date.parse(finish_time.to_s) > week_day && Date.parse(start_time.to_s) < week_day)
      0
    end
  end
end

app/views/reservations/_all_show.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header info-blue">
      <h4 class="modal-title ml-5">予約詳細</h4>
      <button type="button" class="close px-5 lead d-flex align-items-center" data-dismiss="modal" aria-label="閉じる">
        <span aria-hidden="true" class="cross">&times;</span>
       </button>
    </div><!-- /.modal-header  -->
    <%= form_with(model: @reservation, url: reservation_path(@reservation), local: true, method: :patch) do |f| %>
      <div class="modal-body">
        <div class="form-group row">
            <%= f.label "予約者名", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.text_field :user_name, class: 'form-control col-sm-6 ', disabled: "disabled" %>
        </div>
        <div class="form-group row">
            <%= f.label "予約者カナ名", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.text_field :user_kana_name, class: 'form-control col-sm-6', disabled: "disabled" %>
        </div>
        <div class="form-group row">
            <%= f.label "メールアドレス", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.email_field :user_email, class: 'form-control col-sm-6', disabled: "disabled" %>
        </div>
         <div class="form-group row">
            <%= f.label "電話番号", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.telephone_field :user_phone_number, class: 'form-control col-sm-6', disabled: "disabled" %>
        </div>
        <div class="form-group row">
            <%= f.label "生年月日", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.date_field :birthday, class: 'form-control col-sm-6', disabled: "disabled" %>
        </div>
        <div class="form-group row">
            <%= f.label "メニュー", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.collection_select :menu_id, Menu.group(:id).group(:menu_title).order(id: :desc), :id, :menu_title, {prompt: ""}, disabled: "disabled" %>
        </div>
        <div class="form-group row">
            <%= f.label "コース", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.collection_select :course_id, Course.group(:id).group(:course_name).order(id: :desc), :id, :course_name, {prompt: ""}, disabled: "disabled" %>
        </div>
        <div class="form-group row">
          <%= f.label "コース時間", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
          <%= f.text_field :request_course_time, class: 'form-control col-sm-6', readonly: "readonly" %>
        </div>  
        <div class="form-group row">
          <%= f.label "StartTime", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
          <%= raw sprintf(f.datetime_select(
                                        :start_time, 
                                        minute_step: 30,
                                        start_year: Time.now.year,
                                        end_year: Time.now.since(12.month).year,
                                        use_month_numbers: true,
                                        date_separator: '%s', 
                                        time_separator: "%s",
                                        datetime_separator: '%s',
                                        disabled: "disabled"), '年','月', '日',"時")
          %>分
        </div>
        <div class="form-group row">
            <%= f.label "ご要望", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.text_area :demand, class: 'form-control col-sm-6', disabled: "disabled" %>
        </div>
        <div class="error-message text-danger" style="text-align:center;"></div>
        <!--<div class="form-group row">-->
        <!--  <%#= f.label "Usage time", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>-->
        <!--  <#= select_tag('usage_time',options_for_select([[30, 30], [60, 60], [90, 90], [120, 120]]))%>分-->
        <!--</div>-->
      </div><!-- /.modal-body -->
    <% end %>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/reservations/_edit.html.erb
<% provide(:button_text, '更新') %>

<%= include_gon %>

<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header info-blue">
      <h4 class="modal-title ml-5">予約編集画面</h4>
      <button type="button" class="close px-5 lead d-flex align-items-center" data-dismiss="modal" aria-label="閉じる">
        <span aria-hidden="true" class="cross">&times;</span>
       </button>
    </div><!-- /.modal-header  -->
    <%= form_with(model: @reservation, url: reservation_path(@reservation), local: true, method: :patch) do |f| %>
      <div class="modal-body">
        <div class="form-group row">
            <%= f.label "予約者名", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.text_field :user_name, class: 'form-control col-sm-6', required: "required", maxlength: 50 %>
        </div>
        <div class="form-group row">
            <%= f.label "予約者カナ名", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.text_field :user_kana_name, class: 'form-control col-sm-6', required: "required", maxlength: 50 %>
        </div>
        <div class="form-group row">
            <%= f.label "メールアドレス", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.email_field :user_email, class: 'form-control col-sm-6', required: "required" %>
        </div>
         <div class="form-group row">
            <%= f.label "電話番号", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.telephone_field :user_phone_number, class: 'form-control col-sm-6', required: "required", type: "tel" %>
        </div>
        <div class="form-group row">
            <%= f.label "生年月日", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.date_field :birthday, class: 'form-control col-sm-6' %>
        </div>
        <div class="form-group row">
            <%= f.label "メニュー", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.collection_select :menu_id, Menu.group(:id).group(:menu_title).order(id: :desc), :id, :menu_title, {prompt: ""}, required: "required" %>
        </div>
        <div class="form-group row">
            <%= f.label "コース", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <select name="reservation[course_name]" id="reservation_course_name" required="required"></select>
        </div>
        <div class="form-group row">
          <%= f.label "コース時間", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
          <%= f.text_field :request_course_time, class: 'form-control col-sm-6', readonly: "readonly" %>
        </div>
        <div class="form-group row">
          <%= f.label "StartTime", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
          <%= raw sprintf(f.datetime_select(
                                        :start_time,
                                        minute_step: 30,
                                        start_year: Time.now.year,
                                        end_year: Time.now.since(12.month).year,
                                        use_month_numbers: true,
                                        date_separator: '%s',
                                        time_separator: "%s",
                                        datetime_separator: '%s'), '年','月', '日',"時")
          %>分
        </div>
        <div class="form-group row">
            <%= f.label "ご要望", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>
            <%= f.text_area :demand, class: 'form-control col-sm-6', maxlength: 300 %>
        </div>
        <div class="error-message text-danger" style="text-align:center;"></div>
        <!--<div class="form-group row">-->
        <!--  <%#= f.label "Usage time", class: "label-login col-sm-2 lead text-center mr-4 text-sm-right offset-sm-1" %>-->
        <!--  <#= select_tag('usage_time',options_for_select([[30, 30], [60, 60], [90, 90], [120, 120]]))%>分-->
        <!--</div>-->
      </div><!-- /.modal-body -->
      <div class="modal-footer">
        <span class="mx-auto">
          <button type="button" class="btn btn-secondary btn-lg mx-3 px-5" data-dismiss="modal">
            閉じる
          </button>
          <%= f.submit yield(:button_text), class: "btn btn-info btn-lg px-5 mx-3" %>
           <%= link_to "削除", reservation_path(@reservation), method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger btn-lg px-5 mx-3" %>
        </span>
      </div><!-- /.modal-footer -->
    <% end %>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

<script>
$(function() {

  var defaults = $("#reservation_start_time_4i option:selected").val();

  $("#reservation_start_time_4i option").remove();

  var array = [...Array(11).keys()].map(i => ++i + 9);

  $.each(array, function(index, value) {

    if(defaults == value){

       $('#reservation_start_time_4i').append(`<option value="${value}" selected>${value}</option>`);

    }else{

       $('#reservation_start_time_4i').append(`<option value="${value}">${value}</option>`);

    }

  });

  // select要素を予め取得しておく
  var $reservation_menu_id = $('#reservation_menu_id');
  var $reservation_course_name = $('#reservation_course_name');
  var $reservation_request_course_time = $('#reservation_request_course_time');

  //モーダル開いた時にコースを取得
  var $option_tag = $('<option>').val(gon.course_name).text(gon.course_name);
  $reservation_course_name.append($option_tag);

  // メニュー選択時にコースに選択肢を設定
  $reservation_menu_id.change(function(e) {
    var reservation_courses = [];
    var reservation_menu_id = $reservation_menu_id.val();

    $('#reservation_course_name').children().remove();

    // 選択したメニューに紐づくコースの配列を取得
    $.each(gon.course_array, function(index, value) {
      if (value[0] == reservation_menu_id){
        reservation_courses.push(value[1]);
      }
　　});

    // htmlにコースの選択肢のブランクオプションをセット
    var $option_tag = $('<option>').val('').text('選択してください');
      $reservation_course_name.append($option_tag);

    // htmlにコースの選択肢を追加
    reservation_courses.forEach(function(course_name) {

      var $option_tag = $('<option>').val(course_name).text(course_name);
      $reservation_course_name.append($option_tag);
    });
  });


  $reservation_course_name.change(function(e) {
    var reservation_menu_id = $reservation_menu_id.val();
    var reservation_course_name = $reservation_course_name.val();

    // 選択したコースに紐づくコース時間を取得
    $.each(gon.course_time_array, function(index, value) {
      if (value[0] == reservation_menu_id && value[1] == reservation_course_name){
        reservation_course = value[2]
      }
　　});
    // htmlにコース時間を表示
    console.log(reservation_course);
      $reservation_request_course_time.val(reservation_course);
  });



});

// $(document).on('hidden.bs.modal', '.modal', function(){
//       $(this).removeData('bs.modal').empty();
//   });
</script>

app/views/reservations/_reservation_week.html.erb
<%= link_to "<",change_schedule_path(prev:@first_day.ago(7.days)), remote: true, class: "btn btn-outline-secondary" %>
<span class="reservation_week text-wrap font-weight-lighter mx-1 px-1 text-center my-auto"><%= l(@first_day, format: :short_day) %>〜<%= l(@first_day.since(6.days).to_date, format: :short_day) %></span>
<%= link_to ">",change_schedule_path(next:@first_day.since(7.days)),remote:true, class: "btn btn-outline-secondary" %>

app/views/reservations/_reservation_week_tabale_body.html.erb
<table>
  <tbody class="d-block">
    <tr>
      <td class="week-day-th">
        <div>
          <ul class="time-field text-center">
            <% @time_number.each do |time_number| %>
              <li><%= time_number %></li>
            <% end %>
          </ul>
        </div>
      </td>
      <% @week_day.each do |week_day| %>
        <td class="time-schedule">
          <ul>
            <% @times.each do |time| %>
              <% datetime = Time.zone.local(week_day.year,week_day.month,week_day.day,time.hour,time.min) %> 
              <% if datetime >= Time.current %>
                <li class="time-schedule-cell">
                  <%= link_to '', new_reservation_url(:start_time => l(time,format: :shorttime),:week_day => week_day),remote:true %>
                </li>
              <% else %>
                <li class="time-schedule-cell post_time"></li>
              <% end %>
            <% end %>
          </ul>
          <% @day_reservations = @reservations.where(start_time: week_day.in_time_zone.all_day)
          .or(@reservations.where("start_time <= ? and finish_time > ?", week_day.midnight, week_day.midnight)) %>
          <% if @day_reservations.present? %>
            <% @day_reservations.each do |reservation| %>
              <% reservation_height = get_height(reservation.start_time,reservation.finish_time,week_day) %>
              <% top_position = get_position(reservation.start_time,reservation.finish_time,week_day) %>
              <% if admin_signed_in? %>
                <%= link_to(edit_reservation_url(reservation),remote:true,class: 'text-color') do %>
                  <div class="reserved text-center text-truncate" style="height:<%= reservation_height %>px; top:<%= top_position %>px;">
                    <%= reservation.user_name %>様</br>
                    <%= l(reservation.start_time,format: :time) %> 〜 <%= l(reservation.finish_time,format: :time) %>
                  </div>
                <% end %>
              <% else %>
                <div class="reserved text-center" style="height:<%= reservation_height %>px; top:<%= top_position %>px;">
                </div>
              <% end %>
            <% end %>
          <% end %>
        </td>
      <% end %>
    </tr>
 </tbody>
</table>

app/views/reservations/_reservation_week_tabale_th.html.erb
<table border="0" style="border-collapse: collapse">
  <thead>
    <tr>
      <th class="week-day-th"></th>
        <% @week_day.each do |week_day| %>
          <td class="week-day-td <%= get_color(week_day) %>"><%= l(week_day, format: :long_mini) %></td>
        <% end %>
    </tr>
 </thead>
</table>

app/views/reservations/all_index.html.erb
<% provide(:title, '予約一覧') %>

<h2 class="bg_sunflower">予約一覧</h2>
<div class="container text-center">
  <p class="my-5">登録されている予約の確認ができます。</p>

<!-- 検索機能 -->
  <div>
    <%= form_tag(all_reservations_index_path, method: :get, class: "") do %>
      <div class="form-group row">
        <%= label_tag :search_date, "施術日", class: "offset-4" %>
        <%= date_field_tag :search_date, params[:search_date], class: 'form-control col-sm-3 ml-3' %>
      </div>
      <div class="form-group form-check">
        <%= check_box_tag :search_history, {}, false, class: 'form-check-input position-relative'%>
        <%= label_tag :search_history, "過去の履歴を検索" %>
      </div>
      <div class="input-group mx-auto mb-5 w-50">
        <%= text_field_tag :search, params[:search], placeholder: "名前・電話番号・カナ・要望から検索", class: "form-control", 'aria-describedby': "button-addon" %>
        <span class="input-group-append">
          <%= submit_tag '検索', name: :nil, class: "btn btn-info mb-5", id: "button-addon" %>
        </span>
      </div>
    <% end %>
  </div>
  <div class="table-responsive height-fixed scroll">
    <table class="table table-striped text-nowrap" id="table-users">
      <thead class="thead-color lead">
        <tr>
          <th class="center">施術予定日</th>
          <th class="center">名前（カナ）</th>
          <th class="center">電話番号</th>
          <th class="center">メニュー</th>
          <th class="center">コース</th>
          <th class="center">所要時間（分）</th>
          <th class="center">詳細</th>
        </tr>
      </thead>
      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <td class="center"><%= reservation.start_time.strftime("%Y-%m-%d %H:%M") %></td>
            <td class="center"><%= reservation.user_kana_name %></td>
            <td class="center"><%= reservation.user_phone_number %></td>
            <td class="center"><%= reservation.course.menu.menu_title %></td>
            <td class="center"><%= reservation.course.course_name %></td>
            <td class="center"><%= reservation.course.course_time %></td>
          <!-- 予約情報モーダル -->
          <td class="center">

              <%= link_to(all_reservations_show_path(reservation), remote: true, class: "btn btn-lg btn-outline-info d-block d-md-inline-block rounded-circle px-2 py-1 mx-2") do %>
                <i class="fas fa-arrow-up"></i>
              <% end %>


            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <span class="mx-auto">
  <%= paginate @reservations %>
  </span>
</div>

<!-- 予約情報モーダル表示 -->
<div id="all_show" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/reservations/all_show.js.erb
$("#all_show").html("<%= escape_javascript(render 'all_show') %>");
$("#all_show").modal("show");

app/views/reservations/change_schedule.js.erb
$(".reservation_week_form").html("<%= escape_javascript(render :partial => "reservation_week") %>");
$(".reservation_week_form_table").html("<%= escape_javascript(render :partial => "reservation_week_tabale_th") %>");
$(".reservation_week_form_table_body").html("<%= escape_javascript(render :partial => "reservation_week_tabale_body") %>");