config/routes.rb
Rails.application.routes.draw do

  get 'courses/index'
  # resources :meetings
  resources :reservations

  
  devise_for :admins, controllers: { registrations: 'registrations' }
  

  resources :shops, only: [:new, :edit]
  resources :admins, only: [:index, :update, :destroy, :new]
  resources :questions, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :admins, only: [] do
    collection do
      post :generate
    end
  end
  
  resources :menus, only: [] do
    resources :courses, only: :index
  end

  resources :menus, only: [:edit,:create, :update, :delete]
  root 'menus#top'
  get 'change/schedule' => "reservations#change_schedule", as: "change_schedule"
  get 'menus/top' => "menus#top", as: "top"
  get 'menus/course' => "menus#course", as: "course"
  post 'menus/course' => "menus#create", as: "course_new"
  get 'menus/access' => "menus#access", as: "access"
  get 'menus/note' => "menus#note", as: "note"
  get 'menus/add' => "menus#add", as: "add_menu"
  get '/menus/:id/edit_menu' => "menus#edit_menu", as: "renew_menu"
  patch '/menus/:id/edit_menu' => "menus#update_menu"
  delete '/menus/:id/edit_menu' => "menus#destroy"
  
  get 'all_reservations/index' => "reservations#all_index", as: "all_reservations_index"
  get 'all_reservations/:id/show' => "reservations#all_show", as: "all_reservations_show"


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<meta name="robots" content="noindex,nofollow">-->
    <%= display_meta_tags default_meta_tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.11.0/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho" rel="stylesheet">
    <script>$(function(){$('.navbar_toggle').on('click',function(){$(this).toggleClass('open');$('.menu').toggleClass('open');});});</script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    <%= favicon_link_tag('favicon.png') %>


  </head>

  <body>
    <div id="wrapper">
    <header class="sticky-top">
      <!-- 管理者ログイン時のヘッダー -->
      <div id="nav-drawer">
        <% if admin_signed_in? %>
          <%= link_to top_path do %>
            <img src="/images/ichi_logo.png" style="float:right; width:52px; svertical-align: middle;">
          <% end %>
          <input id="nav-input" type="checkbox" class="nav-unshown">
          <label id="nav-open" for="nav-input"><span></span></label>
          <label class="nav-unshown" id="nav-close" for="nav-input"></label>
          <div id="nav-content">
            <ul>
              <li><%= link_to "TOP", top_path %></li>
              <li><%= link_to "コース・料金", course_path %></li>
              <li><%= link_to "よくある質問", questions_path %></li>
              <li><%= link_to "注意事項", note_path %></li>
              <li><%= link_to "アクセス", access_path %></li>
              <li><%= link_to "問い合わせ", "https://docs.google.com/forms/d/e/1FAIpQLSf_2Iu-Ct6soqCbMXCiAI3qrBQsVDkfGmYJr5yXy0wONxkerQ/viewform" %></li>
              <li><%= link_to "予約状況・予約フォーム",  reservations_path %></li>
              <li><%= link_to '管理者について', edit_admin_registration_path, class: "footer-text" %></li>
              <li><%= link_to "ログアウト", destroy_admin_session_path, "data-confirm" => "ログアウトしますか？", method: :delete %></li>
            </ul>
          </div>

          <div id="nav-content-pc">
            <ul>
              <li><%= link_to "TOP", top_path %></li>
              <li><%= link_to "コース・料金", course_path %></li>
              <li><%= link_to "よくある質問", questions_path %></li>
              <li><%= link_to "注意事項", note_path %></li>
              <li><%= link_to "アクセス", access_path %></li>
              <li><%= link_to "問い合わせ", "https://docs.google.com/forms/d/e/1FAIpQLSf_2Iu-Ct6soqCbMXCiAI3qrBQsVDkfGmYJr5yXy0wONxkerQ/viewform" %></li>
              <li><%= link_to "予約状況・予約フォーム",  reservations_path %></li>
              <li><%= link_to '管理者について', edit_admin_registration_path, class: "footer-text" %></li>
              <li><%= link_to "ログアウト", destroy_admin_session_path, "data-confirm" => "ログアウトしますか？", method: :delete %></li>
            </ul>
          </div>
      </div>
      <% else %>

        <!-- 一般ユーザーのヘッダー -->
        <div id="nav-drawer">
          <%= link_to top_path do %>
            <img src="/images/ichi_logo.png" style="float:right; width:52px; vertical-align: middle;">
          <% end %>
          <input id="nav-input" type="checkbox" class="nav-unshown">
          <label id="nav-open" for="nav-input"><span></span></label>
          <label class="nav-unshown" id="nav-close" for="nav-input"></label>
            <div id="nav-content">
              <ul>
                <li><%= link_to "TOP", top_path %></li>
                <li><%= link_to "コース・料金", course_path %></li>
                <li><%= link_to "予約状況・予約フォーム", reservations_path %></li>
                <li><%= link_to "よくある質問", questions_path %></li>
                <li><%= link_to "注意事項", note_path %></li>
                <li><%= link_to "アクセス", access_path %></li>
                <li><%= link_to "問い合わせ", "https://docs.google.com/forms/d/e/1FAIpQLSf_2Iu-Ct6soqCbMXCiAI3qrBQsVDkfGmYJr5yXy0wONxkerQ/viewform" %></li>
              </ul>
            </div>
            <div id="nav-content-pc">
              <ul>
                <li><%= link_to "TOP", top_path %></li>
                <li><%= link_to "コース・料金", course_path %></li>
                <li><%= link_to "予約状況・予約フォーム", reservations_path %></li>
                <li><%= link_to "よくある質問", questions_path %></li>
                <li><%= link_to "注意事項", note_path %></li>
                <li><%= link_to "アクセス", access_path %></li>
                <li><%= link_to "問い合わせ", "https://docs.google.com/forms/d/e/1FAIpQLSf_2Iu-Ct6soqCbMXCiAI3qrBQsVDkfGmYJr5yXy0wONxkerQ/viewform" %></li>
              </ul>
            </div>
        </div>
      <% end %>
    </header>

    <% if flash.present? %>
      <div class="container flash-message-area my-3">
        <% flash.each do |message_type, message| %>
        <%  if message_type == 'notice' %>
          <% message_type = "success" %>
        <% elsif message_type == 'alert' %>
          <% message_type = "danger" %>
        <% end %>
          <div class="alert alert-<%= message_type %> mb-0">
            <%= message %>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= yield %>

    <footer class="footer-color">
      <div class="footer-box footer-text">
        <p class="footer-text"><i class="fas fa-phone fa-flip-horizontal"></i> お電話：03-6904-1073</p><br>
        <p class="footer-text">電話受付時間：9:30〜20:00</p><br>
        <p class="footer-text">※ トリートメント中は電話に出る事ができませんので、メッセージ(お名前、ご連絡先)を残して頂ければ折り返しご連絡いたします。</p>
        <br>
        <% unless current_admin %>
          <%= link_to '管理者はこちら', new_admin_session_path, class: "footer-text" %>
        <% end %>
      </div>

      <%# if Rails.env.development? %>
        <%#= debug params %>
        <%#= debug session[:session_id] %>
        <%#= debug flash %>
      <%# end %>
    </footer>
    </div>
  </body>
</html>